### ISSUE TITLE
Storing keys in a non-extractable way

### ISSUE THREAD

**Issue by panva** [nodejs/webcrypto#13]
In the browser the developer may choose to generate a key pair and store these object instances in [Indexed DB](https://caniuse.com/#feat=indexeddb) and recall these at any point in the future. Like so there's no way to retrieve the private key value, ever.

What are the `extractable: false` options for the node implementation?

**Comment by tniessen** [comment]
You can simulate the browser behavior, but that won't provide the security you are looking for. Browsers provide security by sandboxing user code, but node does not: User code has the same privileges as the node process itself, and can even load univerified native code. So there is really no way to completely prevent malicious code on your own maschine from accessing the private key.

You could also use OpenSSL engines (which would provide better security), but node does not fully support that part yet.

**Comment by panva** [comment]
It does, i'm aware of the why and was just wondering if there's anything you have in store for the future to make it possible. Simulating, well, if i can't recall the key instance in a future process it's pointless then :)

**Comment by tniessen** [comment]
> Simulating, well, if i can't recall the key instance in a future process it's pointless then :)

Sorry, maybe I expressed that inaccurately. I meant that you could write APIs for permanent storage similar to those available in the browser, so the key would not be lost in a future process, but you wouldn't achieve the same level of security since the future node process could just as well access the private key. You could encrypt or wrap the key, but that wouldn't help to protect it from the process itself.

Currently, I can't think of an alternative to OpenSSL engines if you want to achieve the same level of security.

(As always, thanks for sharing your thoughts with us, Filip!)

**Comment by sam-github** [comment]
> Like so there's no way to retrieve the private key value, ever.

I am not certain the browser protection is as good as it may appear. If a key is stored, it, by definition, includes the private key data. The data can be in an obfuscated format (or not), and it can be encrypted with some other key, and there may not be any code around that understand how to decode the key and extract the data, but that doesn't change that it is there, and it can be extracted -- by anyone with the key-encryption-key used to encrypt the stored-key.

Browsers may keep the key-encryption-key "securely" in a way that prevents a web page's js from getting it, but they as well MUST store that key, on disk, so it is persistent across browser restarts. Since browsers prevent web pages from reading arbitrary data from disk, the key-encryption-key can be protected from the web page.

This doesn't apply to node. Node apps have full access to read/write anything the node runtime process can read/write. So, node can, at best "obfuscate" the key.

This is a variant of the DRM problem. If a video player run by a user can decrypt a video and play it, then even if the video player enforces the DRM with its own UI and won't let you export the video, the user can, with sufficient effort, rip the keys the video player has built in to it, and decrypt the video. Same deal with key "non-exportability" and node.

All of which is to say, node WebCrypto can "honor" the non-exportable, but if the key exists in process memory such that its private key data can be used to encrypt/decrypt, then its private key data is accessible to that process, even if it is necessary to use the debug tools APIs or even fork gdb into a child process to get that data. WebCrypto should go for API and behavioural compatibility with the API spec, but document clearly that it may not provide the same security behaviour as browsers do by sandboxing apps.

**Comment by tniessen** [comment]
Exactly my point. I think any attempt of obfuscation would violate Kerckhoff's principle, so I would not advise to do anything in that direction. Encryption using a passphrase that needs to be specified at runtime would work for storage, but I don't think that's what this issue is about.

**Comment by panva** [comment]
Of course the non-extractable is limited by the JS context - that's what I was hoping is planned at some point.

**Comment by tniessen** [comment]
I'll probably add a way to extract non-extractable keys to address this.
